---
- name: Reset UFW rules
  ufw:
    state: reset

- name: Disallow all outgoing traffic
  ufw:
    direction: incoming
    policy: deny

- name: Allow all outgoing traffic
  ufw:
    direction: outgoing
    policy: allow

- name: Allow HTTPS
  ufw:
    rule: allow
    port: '443'

- name: Allow SSH
  ufw:
    rule: allow
    port: '22'

- name: Allow HTTP
  ufw:
    rule: allow
    port: '80'
  when: mdh_node_type == 'primary'

- name: Configure the kernel to keep connections alive before enabling UFW
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Enable UFW
  ufw:
    state: enabled
