---
- name: Install letsencrypt
  apt:
    name: letsencrypt
    state: present

- name: Create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: Install nginx site for letsencrypt
  template:
    src: letsencrypt.j2
    dest: /etc/nginx/sites-available/letsencrypt
    mode: '0644'

- name: Enable letsencrypt site
  file:
    src: /etc/nginx/sites-available/letsencrypt
    dest: /etc/nginx/sites-enabled/letsencrypt
    state: link

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ certbot_admin_email }} --agree-tos -d {{ proxy_grafana_host }}
  args:
    creates: /etc/letsencrypt/live/{{ proxy_grafana_host }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ certbot_admin_email }} --agree-tos -d {{ proxy_grafana_host }} && service nginx reload
