---
- name: Preflight
  include_tasks: preflight.yaml

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
    cache_valid_time: 600

- name: Remove default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Install certbot
  when: mdh_node_type == 'primary'
  include_tasks: certbot.yaml

- name: Install grafana proxy
  when: mdh_node_type == 'primary'
  include_tasks: grafana.yaml

- name: Install mdh proxy
  include_tasks: mdh.yaml
