---
- name: Fail when proxy_mdh_host isn't set
  fail:
    msg: "You need to specify your MD@H account token"
  when: proxy_mdh_host == 'account_token'

- name: Fail when certbot_admin_email isn't set (if primary node)
  fail:
    msg: "You need to specify your Certbot admin email"
  when: mdh_node_type == 'primary' and certbot_admin_email == 'foo@bar.baz'

- name: Fail when proxy_grafana_host isn't set (if primary node)
  fail:
    msg: "You need to specify your MD@H account token"
  when: mdh_node_type == 'primary' and proxy_grafana_host == 'grafana.example.com'
